In [1]:
import numpy as np

In [17]:
A = np.array([[1,0],
             [0,1],
             [0,0]])

In [18]:
b = np.array([5,5,0])

In [20]:
Ainv = np.linalg.pinv(A)
# pseudo code

In [21]:
x = Ainv@b

In [22]:
A@x - b

array([0., 0., 0.])

In [23]:
print(x)

[5. 5.]


벡터 w를 벡터 u, v의 선형결합으로 표현하기!!!!!!

In [40]:
u = np.array([1,-2,-5])
v = np.array([2,5,6])
w = np.array([7,4,-3])

In [51]:
A = np.append(u,v)

print("A = ")
print(A)

A = A.reshape((2,3))

A = np.transpose(A)

print("A =")
print(A)

b = np.array([7,4,-3])

print("b = ")
print(b)

A = 
[ 1 -2 -5  2  5  6]
A =
[[ 1  2]
 [-2  5]
 [-5  6]]
b = 
[ 7  4 -3]


In [53]:
Ainv = np.linalg.pinv(A)

In [54]:
x = Ainv@b
print(x)
print(A@x - b)
# 올바른 해인지 확인
# pseudo 역행렬로 제대로 안 구해질
# 수도 있다.

[3. 2.]
[-1.77635684e-15  8.88178420e-16  4.88498131e-15]
